import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import { JwtService } from '@nestjs/jwt';
import { AuthService } from '../src/auth/auth.service';
import { EmailService } from '../src/auth/email.service';
import { User } from '../src/user/entity/user.entity';
import { OnlineFixture, startOnlineFixture } from './online-fixture';

const { chromium } = require(process.env.ARCADE_PLAYWRIGHT_MODULE ||
  '/opt/miniconda3/lib/python3.12/site-packages/playwright/driver/package');
const evidence = process.env.ARCADE_EVIDENCE_DIR
  ? resolve(process.env.ARCADE_EVIDENCE_DIR)
  : resolve(__dirname, '../../docs/home-online-polish/evidence');
const intentKey = 'transcendence.online-intent.v1';

/** Real browser + signed fixture credentials + production guards/endpoints.
 * Account preconditions and the 2FA code are prepared in an owned fixture only.
 * This is not an OAuth, mail-delivery, or guest full-redirect test.
 */
describe('Home online intent respects actual authentication prerequisites', () => {
  let fixture: OnlineFixture;
  let browser: any;
  let browserVersion = '';
  let quietLogs: jest.SpyInstance;
  let mail: jest.SpyInstance;
  const contexts: any[] = [];
  const results: Array<Record<string, unknown>> = [];
  let stage = 'setup';

  beforeAll(async () => {
    // Legacy AuthService logs its verification code. Never allow that in evidence.
    quietLogs = jest.spyOn(console, 'log').mockImplementation(() => undefined);
    fixture = await startOnlineFixture({ serveFrontend: true, includeServices: true });
    mail = jest.spyOn(fixture.app.get(EmailService), 'sendJoinMail');
    browser = await chromium.launch({ headless: true, executablePath: process.env.ARCADE_CHROMIUM_EXECUTABLE ||
      '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
    browserVersion = browser.version();
    mkdirSync(evidence, { recursive: true });
  }, 30000);

  afterAll(async () => {
    const mailCalls = mail?.mock.calls.length ?? 0;
    for (const context of contexts) await context.close();
    if (browser) await browser.close();
    if (fixture) await fixture.close();
    quietLogs?.mockRestore();
    writeFileSync(resolve(evidence, 'home-auth-prerequisites.json'), JSON.stringify({
      scope: 'Isolated PostgreSQL schema; real Nest JWT/User guards and auth/profile endpoints; Playwright Chromium',
      credentials: 'Real valid or expired signed fixture JWT injected into browser localStorage; values never recorded',
      twoFactor: 'Code generated by existing AuthService in memory; real verification form and endpoint; no external email',
      createdAt: new Date().toISOString(), browserVersion, viewport: { width: 1440, height: 900 }, fullPageScreenshots: true,
      frontendScripts: [...readFileSync(resolve(__dirname, '../../frontend/dist/index.html'), 'utf8').matchAll(/js\/[^"\s]+\.js/g)].map((match) => match[0]),
      externalMailCalls: mailCalls,
      results,
    }, null, 2));
  }, 15000);

  async function pageWithCredential(credential: string) {
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
    contexts.push(context);
    await context.addInitScript((value: string) => localStorage.setItem('token', value), credential);
    const page = await context.newPage();
    const observations = { sockets: 0, currentUserStatuses: [] as number[], pageErrors: 0 };
    page.on('websocket', () => { observations.sockets++; });
    page.on('pageerror', () => { observations.pageErrors++; });
    page.on('response', (response: any) => {
      if (new URL(response.url()).pathname === '/user/me') observations.currentUserStatuses.push(response.status());
    });
    return { page, observations };
  }

  async function scenario(name: string, run: () => Promise<Record<string, unknown>>) {
    try {
      results.push({ name, status: 'PASS', ...await run() });
    } catch {
      // Avoid leaking a fixture credential, account address, or entered verification
      // code through a third-party browser error's call log.
      results.push({ name, status: 'FAIL', stage });
      throw new Error(`${name} failed at ${stage}; inspect the sanitized fixture report`);
    }
  }

  it('rejects an actually expired signed JWT before any online socket is created', async () => {
    await scenario('expired-signed-jwt', async () => {
      stage = 'prepare-expired-jwt';
      const player = await fixture.createPlayer();
      const jwt = fixture.app.get(JwtService);
      const token = jwt.sign({ username: player.name }, { secret: process.env.SECRET, expiresIn: -60 });
      expect(() => jwt.verify(token, { secret: process.env.SECRET, ignoreExpiration: true })).not.toThrow();
      expect(() => jwt.verify(token, { secret: process.env.SECRET })).toThrow('jwt expired');
      const { page, observations } = await pageWithCredential(token);
      stage = 'protected-route-rejection';
      await page.goto(fixture.httpUrl + '/game');
      await page.waitForURL((url: URL) => url.pathname === '/login');
      await page.getByRole('heading', { name: /온라인 대전/ }).waitFor();
      await page.waitForTimeout(300);
      expect(observations.currentUserStatuses).toContain(401);
      expect(observations.sockets).toBe(0);
      expect(observations.pageErrors).toBe(0);
      expect(await page.evaluate(() => localStorage.getItem('token') === null)).toBe(true);
      const screenshot = 'auth-expired-token-login.png';
      await page.screenshot({ path: resolve(evidence, screenshot), fullPage: true });
      return { http401: true, onlineSockets: observations.sockets, tokenCleared: true, route: '/login', screenshot };
    });
  });

  it('retains the intended game behind missing-nickname setup and resumes after the actual profile form', async () => {
    await scenario('missing-nickname-before-game', async () => {
      stage = 'prepare-missing-nickname';
      const player = await fixture.createPlayer();
      await fixture.dataSource.getRepository(User).update(player.id, { nickname: null });
      const { page, observations } = await pageWithCredential(fixture.browserCredential(player));
      stage = 'nickname-guard';
      await page.goto(fixture.httpUrl + '/game');
      await page.waitForURL((url: URL) => url.pathname === '/info');
      await page.getByPlaceholder('Choose a unique name').waitFor();
      expect(observations.sockets).toBe(0);
      expect(await page.evaluate((key: string) => JSON.parse(sessionStorage.getItem(key) || 'null')?.destination, intentKey)).toBe('/game');
      const before = 'auth-nickname-prerequisite.png';
      await page.screenshot({ path: resolve(evidence, before), fullPage: true });
      stage = 'real-nickname-form';
      await page.getByPlaceholder('Choose a unique name').fill('AuthReady');
      const [patched] = await Promise.all([
        page.waitForResponse((response: any) => new URL(response.url()).pathname === '/user/nickname' && response.request().method() === 'PATCH'),
        page.getByRole('button', { name: 'Choose', exact: true }).click(),
      ]);
      expect(patched.status()).toBe(200);
      await page.waitForURL((url: URL) => url.pathname === '/game');
      await page.getByTestId('online-play').waitFor();
      await page.waitForFunction(() => !(document.querySelector('[data-testid="online-play"]') as HTMLButtonElement)?.disabled);
      expect(await page.evaluate((key: string) => sessionStorage.getItem(key) === null, intentKey)).toBe(true);
      const persisted = await fixture.dataSource.getRepository(User).findOneByOrFail({ id: player.id });
      expect(persisted.nickname).toBe('AuthReady');
      expect(observations.sockets).toBe(1);
      expect(observations.pageErrors).toBe(0);
      const after = 'auth-nickname-resumed-game.png';
      await page.screenshot({ path: resolve(evidence, after), fullPage: true });
      return { prerequisiteRoute: '/info', nicknamePatchStatus: 200, finalRoute: '/game', persistedNickname: true,
        socketsBeforeSetup: 0, socketsAfterSetup: 1, singleUseIntent: true, screenshots: [before, after] };
    });
  });

  it('keeps 2FA required until the original verification form succeeds, without sending external mail', async () => {
    await scenario('two-factor-before-game', async () => {
      stage = 'prepare-two-factor';
      const player = await fixture.createPlayer();
      await fixture.dataSource.getRepository(User).update(player.id, { need2fa: true, is2fa: false });
      const code = await fixture.app.get(AuthService).createCode(player.email);
      if (!code || code.length !== 6) throw new Error('Fixture code unavailable');
      const { page, observations } = await pageWithCredential(fixture.browserCredential(player));
      stage = 'two-factor-guard';
      await page.goto(fixture.httpUrl + '/game');
      await page.waitForURL((url: URL) => url.pathname === '/tfa');
      await page.getByPlaceholder('type six digits code').waitFor();
      expect(observations.currentUserStatuses).toContain(403);
      expect(observations.sockets).toBe(0);
      expect(await page.evaluate((key: string) => JSON.parse(sessionStorage.getItem(key) || 'null')?.destination, intentKey)).toBe('/game');
      stage = 'real-two-factor-form';
      await page.getByPlaceholder('example@student.42seoul.kr', { exact: false }).fill(player.email);
      await page.getByPlaceholder('type six digits code').fill(code);
      const [verified] = await Promise.all([
        page.waitForResponse((response: any) => new URL(response.url()).pathname === '/auth/email/verify'),
        page.getByRole('button', { name: 'Verify', exact: true }).click(),
      ]);
      expect(verified.status()).toBe(200);
      await page.waitForURL((url: URL) => url.pathname === '/game');
      await page.getByTestId('online-play').waitFor();
      await page.waitForFunction(() => !(document.querySelector('[data-testid="online-play"]') as HTMLButtonElement)?.disabled);
      const persisted = await fixture.dataSource.getRepository(User).findOneByOrFail({ id: player.id });
      expect(persisted.need2fa && persisted.is2fa).toBe(true);
      expect(await page.evaluate((key: string) => sessionStorage.getItem(key) === null, intentKey)).toBe(true);
      expect(observations.sockets).toBe(1);
      expect(observations.pageErrors).toBe(0);
      expect(mail).not.toHaveBeenCalled();
      return { prerequisiteRoute: '/tfa', http403BeforeVerification: true, verifyEndpointStatus: 200,
        finalRoute: '/game', persistedVerifiedFlag: true, socketsBeforeVerification: 0,
        socketsAfterVerification: 1, singleUseIntent: true, externalMailCalls: 0 };
    });
  });
});
